---
# need to keep these seperate so seperate callback events fire
- name: Start and enable nginx services
  service:
    name: nginx 
    state: started
    enabled: yes
- name: Start and enable 8ball services
  service:
    name: "{{ eightball_service_name }}"
    state: started
    enabled: yes
