---
- name: Create user the will run the 8ball-service
  user:
    name: "{{ eightball_owner }}" 
    groups: "{{ eightball_group }}"
    append: yes
- name: Create directories for 8ball-service
  file:
    state: directory
    path: "{{ item }}"
    owner: "{{ eightball_owner }}"
    group: "{{ eightball_group }}" 
  with_items:
    - "{{ eightball_base_path }}"
    - "{{ eightball_config_path }}"
- name: Create log for 8ball-service
  file:
    state: touch
    path: "{{ eightball_logto_file }}"
    owner: "{{ eightball_owner }}"
    group: "{{ eightball_group }}" 
- name: Install 8-ball service from git repo
  git:
    repo: "{{ eightball_git_repo }}"
    dest: "{{ eightball_base_path }}"
    version: "{{ eightball_git_version | default(omit) }}"
  notify:
    - restart 8ball-service
