---
# handlers file for 8ball-service
- name: restart nginx
  service:
    name: nginx
    state: restarted

- name: restart 8ball-service
  service:
    name: "{{ eightball_service_name }}"
    state: restarted
