---
# defaults file for 8ball-server
eightball_service_name: 8ball-server
eightball_base_path: /srv/8ball-server
eightball_service_file: /etc/systemd/system/{{ eightball_service_name }}.service
eightball_nginx_conf: /etc/nginx/conf.d/8ball.conf
eightball_uwsgi_ini: "{{ eightball_base_path }}/8ball.ini"
eightball_8ball_conf: "{{ eightball_base_path }}/8ball.conf"
eightball_git_repo: git://github.com/tima/8ball-server.git
eightball_owner: uwsgi
eightball_group: nginx
eightball_metrics_enabled: False
eightball_metrics_ms_rounding: False

