---
- hosts: "{{ eightball_hosts | default('8balls') }}"
  name: "Installation and configuration 8ball-servers [CentOS7]"
  become: yes
  vars:
    # eightball_git_version: wsgi
  roles:
    - tima.epel-repo
    - 8ball-server
